### ISSUE TITLE
unnecessary BR/gtk => 3.18

### ISSUE THREAD

**Issue by region51** [UnitedRPMs/gnome-mpv#1]
@paulcarroty зачем портишь спек???

unnecessary BR
```
BuildRequires:  autoconf-archive
BuildRequires:  automake
```
automake, autoconf-archive это для Source code (tar.gz)

https://github.com/gnome-mpv/gnome-mpv/issues/155

```
%global gtk3_version 3.20
-->
%global gtk3_version 3.18
```

https://github.com/RussianFedora/gnome-mpv/blob/master/gnome-mpv.spec

P.S. И вообще-то, хорошим тоном считается ведение changelog'а.
P.P.S. И последний вопрос, ты вообще что-нибудь в этом понимаешь?  Так как мне непонятны совершенно твои телодвижения.

**Comment by paulcarroty** [comment]
Fixed by https://github.com/UnitedRPMs/gnome-mpv/commit/c5e89e82bdb325e64cac0446f88424a3449f4b28.

**Comment by region51** [comment]
То есть ответить не судьба.
Н-даа, беда и ужас неописуеммый. Удачи недопроекту.

**Comment by paulcarroty** [comment]
@region51 что именно не понятно? Ошибки внезапно бывают у всех.

**Comment by region51** [comment]
>Ошибки внезапно бывают у всех

Да какие ошибки, я специально привел спек к такому виду, а ты просто скопипастил его с детскими ошибками и написал просто Update to 0.9.

**Comment by paulcarroty** [comment]
> А если ты ничего не понимаешь, то бери просто спек и ничего, ничего не меняя определяешь здесь.

Нафиг надо. 3.20 я поставил, так как 3.18 у нас банально нет. Те две зависимости были оставлены на всякий случай, ибо упоминаются в проекте. Вопросы?

**Comment by region51** [comment]
>Нафиг надо. 3.20 я поставил, так как 3.18 у нас банально нет. Те две зависимости были оставлены на всякий случай, ибо упоминаются в проекте. Вопросы?

Даааа, удачи.
http://copr-dist-git.fedorainfracloud.org/cgit/paulcarroty/test/gnome-mpv.git/diff/?id=cd42e32bb9e75c7e1252ce49203568e8eba45049&id2=18aa45776563d9e698d65e63f773efc94843d5a5

**Comment by paulcarroty** [comment]
@region51 остальные ограничения по версиях абсолютно бессмысленны для F24.

**Comment by region51** [comment]
>остальные ограничения по версиях абсолютно бессмысленны для F24.

да причем здесь это, я про то, раз вы определили пакет к себе, то и заниматься должны уже вы им, а получается наоборот, я все делаю, а ты просто по неумному чуток корректируешь (и это факт) и вуаля новая версия у вас готова.

**Comment by region51** [comment]
Умей отвечать за свои поступки.
Бред. В первый раз такое вижу на git'e, чтобы тупо потерли абсолютно нормальный, адекватный разговор.
