### ISSUE TITLE
No volume control by mouse wheel

### ISSUE THREAD

**Issue by MichSt** [UnitedRPMs/gnome-mpv#2]
Overview Description:
Volume control

Steps to Reproduce:
Bind keys ~/.config/mpv/input.conf
MOUSE_BTN3 add volume 2
MOUSE_BTN4 add volume -2

Actual Results:
No result but other buttons work

Expected Results:
))))

Version:
Gnome-mpv 0.9, Fedora 24, Gnome 3.20.2

The developers fixed in [04efbc3](https://github.com/gnome-mpv/gnome-mpv/commit/04efbc3f1090a69eb33615af601846718599e821). a month ago.

**Comment by paulcarroty** [comment]
@MichSt the latest version from git was added to repository, test it.

**Comment by MichSt** [comment]
Everything is working. Thank you.
